name: Generate and Deploy AsyncAPI Docs

on:
  push:
    branches: ["master"]  # Trigger on push to main
    paths:
      - 'specs/redispatching-openapi.yml' # Only run if the yaml file changes
      - '.github/workflows/openapi-docs.yml'

# Permissions required to push the generated HTML to the gh-pages branch
permissions:
  contents: write

jobs:
  generate-docs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      
      - name: Create Output Folder
        run: mkdir -p docs-output
      
      - name: Generate HTML documentation
        run: npx @redocly/cli build-docs pecs/redispatching-openapi.yml -o docs-output/index-openapi.html      

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs-output